name: Build and publish 

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      continue: 'false'
    strategy:
      matrix:
        service:
          - name: "ttacompu/auction-svc"
            path: 'src/AuctionService'
          - name: "ttacompu/search-svc"
            path: 'src/SearchService'
          - name: "ttacompu/bid-svc"
            path: 'src/BiddingService'
          - name: "ttacompu/identity-svc"
            path: 'src/IdentityService'
          - name: "ttacompu/gateway-svc"
            path: 'src/GatewayService'
          - name: "ttacompu/notify-svc"
            path: 'src/NotificationService'
          - name: "ttacompu/web-app"
            path: 'frontend/web-app'
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for changes in service path
      run : |
        if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
          echo "No changes in ${{matrix.service.path}}, skipping build and push."
          echo "continue = false" >> $GITHUB_ENV
          exit 0
        else
          echo "Changes detected in ${{matrix.service.path}}, proceeding with build and push."
          echo "continue = true" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      if: env.continue == 'true'
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      if: env.continue == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      if: env.continue == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.service.path }}/Dockerfile
        push: true
        tags: ${{ matrix.service.name }}:latest
  